Part5
iodum/thinknetica pull request #3
Opened 2016-10-27 21:55 UTC by iodum

2016-10-28 09:36 UTC, palkan requested changes

2016-10-28 09:36 UTC, palkan commented on app/controllers/answers_controller.rb
> +    @answer.user = current_user
А зачем здесь нам `user`? У нового ответа еще нет автора.

2016-10-28 09:36 UTC, palkan commented on spec/acceptance/answers/create_spec.rb
> +    expect(page).to have_content 'Your answer successfully added.'
Нам в первую очередь нужно проверить, что на станице появился введенный нами контент (текст).

2016-10-28 09:36 UTC, palkan commented on spec/acceptance/answers/create_spec.rb
> +  scenario 'Authenticated user can add answer on question page' do
Этот сценарий избыточный, мы уже проверяем это в первом.

2016-10-28 09:36 UTC, palkan commented on spec/acceptance/questions/create_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Здесь то же самое: надо проверить контент вопроса.

2016-10-28 09:36 UTC, palkan commented on spec/acceptance/questions/index_spec.rb
> +  given!(:questions) { create_list(:question, 5) }
Достаточно 2х, не нужно создавать лишние данные, это замедляет тесты.

Для этого есть метод `create_pair(:question)`.

2016-10-28 09:36 UTC, palkan commented on spec/factories/answers.rb
> +    body "MyAnswer"
У тебя есть тест, в котором ты проверяешь вывод списка ответов по их телу.
Но если у них одинаковый контент, тест будет проходить, даже если на самом деле будет выводится один ответ.

Нужно сделать тело ответа уникальным.

2016-10-28 09:36 UTC, palkan commented on spec/factories/questions.rb
>      title "MyString"
Здесь та же проблема с уникальностью.

2016-10-28 09:36 UTC, palkan commented on spec/factories/questions.rb
> +        answer_count 5
2

2016-10-29 09:16 UTC, vkurennov requested changes
Исправь замечания

2016-10-29 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @user = current_user
А зачем в переменную помещать current_user? Ведь метод current_user и в видах доступен.

2016-10-29 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
У нас форма ответа должна быть на странице вопроса (согласно заданию), поэтому в случае ошибки и рендерить надо страницу вопроса (question/show)

2016-10-29 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def destroy
В контроллере обязательно должна быть проверка на авторство, ведь можно сделать запрос в обоход интерфейса и удалить чужой ответ

2016-10-29 09:16 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'answers/form'
Вот у тебя форма ответа, соответственно при ошибках валидации, надо эту страницу рендерить, а не answers/new

2016-10-29 09:16 UTC, vkurennov commented on spec/acceptance/questions/create_spec.rb
> +    expect(page).to have_content data[:body]
Надо и заголовок проверить

2016-10-29 09:16 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора и для не-автора

2016-10-29 09:16 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>          expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
Тут надо проверить, что созданный вопрос связыается с залогиненным юзером

2016-10-29 09:16 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Должно быть 2 контекста: для автора и для не автора

2016-10-29 09:16 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
Где тесты на метод User#author_of?

2016-10-31 20:23 UTC, vkurennov approved these changes
Принято, но поправь замечания

2016-10-31 20:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.author_of?(@question)
А если это не автор? Рельсы попытаются отрендерить вид destroy.html.erb, не найдут его и выдадут 500-ю ошибку

2016-10-31 20:23 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { answer: attributes_for(:answer),
Надо проверять и на связь с вопросом и на связь с юзером. Это не две взаимоисключающие проверки, а две взаимодополняющие. Т.е. должно быть 2 разных теста на разные связи

2016-11-01 17:39 UTC, merged