Part7
iodum/thinknetica pull request #5
Opened 2016-11-07 16:41 UTC by iodum

2016-11-07 18:40 UTC, vkurennov requested changes
Исправь замечания

2016-11-07 18:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer)
А что если условие не выполнится? Рельсы ведь все равно будут рендерить update.js.erb, но зачем?

2016-11-07 18:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      if current_user.author_of?(@answer)
И тут надо как-то отработать ситуацию, если условие не выполняется

2016-11-07 18:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer.question)
Ну и тут нужна отработка невыполнения условия. Подскажу: сделай общий js-вид, который выводит сообщение о том, что нет прав на совершение действия и рендери его.

2016-11-07 18:40 UTC, vkurennov commented on app/views/answers/accept.js.erb
> +
Удаляй лишние пустые строки, оставляй только последнюю (так требует git)

2016-11-07 18:40 UTC, vkurennov commented on app/views/answers/create.js.erb
Лишние строки

2016-11-07 18:40 UTC, vkurennov commented on app/views/answers/update.js.erb
> +
Лишние строки

2016-11-07 18:40 UTC, vkurennov commented on app/views/questions/update.js.erb
> +
Лишние строки

2016-11-07 18:40 UTC, vkurennov commented on spec/acceptance/answers/accept_spec.rb
> +  scenario 'Try to accept answer for other user\'s question' do
Еще надо проверить, что незалогиненный юзер не видит ссылки

2016-11-07 18:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer.body).to eq answer.body
Ну тут проверка без проверки. Ты сравниваешь одно и то же значение, само собой, оно будет равно самому себе. Надо сохранить предыдущее значение, до обновления и сравнивать с новым, либо проверять, что текущее значение не равно тому, что было в параметрах запроса.

2016-11-07 18:40 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer2.reload).to be_accepted
В юнит-тестах действует правило "один тест - один expect", поэтому надо разделить на 2 теста: один проверяет, что ответ, у которого вызван метод accept становится accepted, второй - что если уже есть лучший ответ, то он теряет этот флаг.

2016-11-08 13:14 UTC, iodum commented on spec/acceptance/answers/accept_spec.rb
> +  scenario 'Try to accept answer for other user\'s question' do
Проверяется выше, 14 строка

2016-11-08 16:02 UTC, vkurennov approved these changes

2016-11-09 09:56 UTC, merged